service:
  golangci-lint-version: 1.27.x

run:
  deadline: 5m

linters:
  enable-all: true

  # linters are disabled if their majority of issues is considered false-positive (intended code)
  # and the remaining issues (if existing) aren't worth it.
  disable:

issues:
  exclude-use-default: false # disable filtering of defaults for better zero-issue policy
  exclude:
  max-per-linter: 0 # disable limit; report all issues of a linter
  max-same-issues: 0 # disable limit; report all issues of the same issue

linters-settings:
  lll:
    line-length: 160
