references:
  linuxKernel: "https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=49decddd39e5f6132ccd7d9fdc3d7c470b0061bb"
  cnetTwitter: "https://www.cnet.com/news/twitter-engineers-replace-racially-loaded-tech-terms-like-master-slave/"
  googleDoc: "https://developers.google.com/style/inclusive-documentation"
  googlePronouns: "https://developers.google.com/style/pronouns#gender-neutral-pronouns"

formatting:
  # To exclude the long-form of the references is the default,
  # yet it is included here to showcase the full list of possibilities.
  withReferences: false

phrases:
  - synonyms: [master, masters]
    alternatives: [primary, leader, main]
    references: [linuxKernel, cnetTwitter]

  - synonyms: [slave, slaves]
    alternatives: [secondary, follower, replica, standby]
    references: [linuxKernel, cnetTwitter]

  - synonyms: [whitelist, whitelists]
    alternatives: [allowlist, passlist]
    references: [linuxKernel, cnetTwitter]

  - synonyms: [grandfathered]
    alternatives: [legacy status]
    references: [cnetTwitter]

  - synonyms: [guy, guys]
    alternatives: [people, folks, you all]
    references: [cnetTwitter]

  - synonyms: [he, his, him, she, her]
    alternatives: [their, them]
    references: [googlePronouns, cnetTwitter]

  - synonyms: [man hour, man hours]
    alternatives: [person hours, engineer hours]
    references: [googleDoc, cnetTwitter]

  - synonyms: [dummy, dummies]
    alternatives: [placeholder, sample]
    references: [googleDoc, cnetTwitter]

  - synonyms: [sanity check, sanity checks]
    alternatives: [quick check]
    references: [googleDoc, cnetTwitter]
