name: self-lint
on: [push, pull_request]
jobs:
  self:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'
      - uses: actions/checkout@v2
      - name: Download modules
        run: go mod tidy -v
      - name: Build binary
        run: go install ./cmd/goconsider
      - name: Run goconsider
        run: $(go env GOPATH)/bin/goconsider ./...
